# -----------------
#  Site
# -----------------

timezone: UTC

title: Sw/eden APT
description: APT Packages Information


defaults:
  - scope:
      path: ""
      type: "packages"
    values:
      layout: "package"

# -----------------
#  APT
# -----------------
apt:
  # Default APT domain.
  domain: apt.eossweden.org
  # Staticly define the components and the order (most used ones first)
  components:
    - stable
    - edge
    - testing

# -----------------
#  Collections
# -----------------
collections:
  repos:
    permalink: "/:name"
    output: true
  packages:
    permalink: "/:path"
    output: true

# -----------------
#  Build config
# -----------------

sass:
  # Compress (minify) css output.
  style: compressed
